// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_401 from "./routes/401.tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $Simulation from "./islands/Simulation.tsx";
import * as $SimulationWrapper from "./islands/SimulationWrapper.tsx";
import * as $islandTypes from "./islands/islandTypes.ts";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/401.tsx": $_401,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/joke.ts": $api_joke,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/Simulation.tsx": $Simulation,
    "./islands/SimulationWrapper.tsx": $SimulationWrapper,
    "./islands/islandTypes.ts": $islandTypes,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
